version: "3.3"

services:

  voyant_gen:
    build:
      context: ./compose/voyant_generator
    volumes:
      - ${LOCAL_VOL}:${CONTAINER_VOL}

  jekyll_gen:
    build:
      context: ./compose/jekyll_generator
    volumes:
      - ${LOCAL_VOL}:${CONTAINER_VOL}
    depends_on:
      - voyant_gen
